# Generated by Django 4.2.23 on 2025-09-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(max_length=50, verbose_name='Número o Identificador de Casa')),
                ('cantidad_familia', models.PositiveIntegerField(default=1)),
                ('consejo_comunal', models.CharField(max_length=200, verbose_name='Consejo Comunal')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('papelera', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_cedula', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1)),
                ('cedula_numero', models.CharField(max_length=9, unique=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('papelera', models.BooleanField(default=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_administrativa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(choices=[('texto', 'Texto'), ('opcion_multiple', 'Opción Múltiple'), ('opcion_unica', 'Opción Única'), ('si_no', 'Sí/No')], max_length=20)),
                ('tipo_respuesta', models.CharField(choices=[('texto', 'Texto'), ('opcion_multiple', 'Opción Múltiple'), ('opcion_unica', 'Opción Única'), ('si_no', 'Sí/No')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('requerida', models.BooleanField(default=False)),
                ('titulo_campo_texto', models.CharField(blank=True, help_text="Título del campo de texto adicional para respuesta 'Sí'.", max_length=100, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioBasico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaludPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otros_patologias', models.TextField(blank=True, null=True)),
                ('otros_medicamentos', models.TextField(blank=True, null=True)),
                ('otros_insumos', models.TextField(blank=True, null=True)),
                ('encuestado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='encuesta.encuestado')),
                ('insumos', models.ManyToManyField(blank=True, to='encuesta.insumomedico')),
                ('medicamentos', models.ManyToManyField(blank=True, to='encuesta.medicamento')),
                ('patologias', models.ManyToManyField(blank=True, to='encuesta.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('papelera', models.BooleanField(default=False)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
                ('encuestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuestado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/perfiles/', verbose_name='Avatar')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255)),
                ('item_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuesta.itemencuesta')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, max_length=255, null=True)),
                ('valor_respuesta', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('encuestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuesta.encuestado')),
                ('item_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuesta.itemencuesta')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_opcion', to='encuesta.opcionpregunta')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_respuesta', to='encuesta.respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='encuestas/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='encuesta.encuesta')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personas en la Familia')),
                ('nombre_familia', models.CharField(blank=True, max_length=100)),
                ('jefe_familia', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=11, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='encuesta.casa')),
            ],
        ),
        migrations.AddField(
            model_name='encuestado',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='encuesta.familia'),
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Comunidad')),
                ('estado', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta_Amacuro', 'Delta Amacuro'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva_Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Vargas', 'Vargas'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad_habitantes', models.IntegerField(default=0)),
                ('papelera', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='encuesta.comunidad'),
        ),
        migrations.CreateModel(
            name='CasaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_servicio', models.BooleanField(default=False)),
                ('calidad_servicio', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='regular', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='encuesta.casa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='encuesta.serviciobasico')),
            ],
            options={
                'unique_together': {('casa', 'servicio')},
            },
        ),
    ]
