# Generated by Django 4.2.23 on 2025-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestado',
            name='familia',
        ),
        migrations.AlterField(
            model_name='encuestado',
            name='cedula_numero',
            field=models.CharField(max_length=9),
        ),
        migrations.AddConstraint(
            model_name='encuestado',
            constraint=models.UniqueConstraint(condition=models.Q(('papelera', False)), fields=('cedula_numero',), name='unique_cedula_if_not_in_papelera'),
        ),
    ]
