# Generated by Django 4.2.23 on 2025-10-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_remove_encuestado_familia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='encuesta.comunidad'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='estado',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Vargas', 'Vargas'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='encuesta.encuesta'),
        ),
    ]
