# Generated by Django 4.2.23 on 2025-10-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_fotografia_comunidad_alter_comunidad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestado',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='encuesta.familia'),
        ),
    ]
