# Generated by Django 4.2.23 on 2025-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_encuestado_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='identificador_extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador Extra (Referencia, Calle, etc.)'),
        ),
    ]
