# Generated by Django 4.2.23 on 2025-10-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_casa_identificador_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comunidad',
        ),
    ]
