# Generated by Django 4.2.23 on 2025-10-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_auto_20251003_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.DeleteModel(
            name='CasaServicio',
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='InsumoMedico',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='Patologia',
        ),
        migrations.DeleteModel(
            name='SaludPersona',
        ),
        migrations.DeleteModel(
            name='ServicioBasico',
        ),
    ]
